### ISSUE TITLE
feat(demo-version): add instructions for using demo submission version branch

### ISSUE THREAD

**Issue by antonioruizcortes** [isa-group/Pricing4Java#12]
We should make it easier for colleagues to review the demos that can be made with this library. It would be necessary to outline a strategy so that they can review the codebase of the submitted version at any time and that the library can continue to be versioned for other purposes. Perhaps a branch could be an approach worth considering.

**Comment by Alex-GF** [comment]
We've adopted the suggestion to create a separate branch for easier review of the demos made with our library. 

The new branch, named **ICWE2024-Demo_Version**, contains the version of the demo presented for ICWE 2024. This will allow colleagues to review the demo-specific codebase at any time, while we continue to version the library for other developments. 

Feel free to check out the branch and share your feedback.
